/* 2026-09-22: dated ticket quotes and route-based dining estimates. */
const diningDays = [
  {date:'9月29日',city:'旧金山',low:650,high:950,brief:'生蚝、海鲜汤／日式拉面',note:'落地日不预约长时间正餐。两餐之外含咖啡及饮水。',meals:[
    {time:'14:00左右 · 午餐',name:'Hog Island Oyster Co.（霍格岛生蚝餐厅）',where:'1 Ferry Building, San Francisco',price:'¥350–550',dish:'少量生蚝、蛤蜊浓汤、面包；不吃生食就选熟海鲜。',why:'就在渡轮大楼内，不另绕路。周二11:30–20:00；排队超过25分钟改同楼汉堡店。',source:'https://hogislandoysters.com/restaurants/san-francisco/',xhs:'https://www.xiaohongshu.com/explore/67bddb1e000000002a001bd9',tip:'桌边服务：税前18%–20%。'},
    {time:'19:45–20:30 · 晚餐',name:'Marufuku Ramen（丸福拉面）',where:'1581 Webster St, San Francisco',price:'¥260–350',dish:'两碗豚骨或鸡白汤拉面；可加一份炸鸡共享。',why:'日本城内，吃完回安妮女王酒店。官网页面出现两套营业时段，不把它当深夜店；从金门大桥返回后约19:45到，提前核对最后点单时间；排队过久就近换店。',source:'https://www.marufukuramen.com/sanfrancisco',tip:'桌边服务：税前18%–20%。'},
    {time:'午餐省钱替换',name:"Gott’s Roadside（戈茨汉堡店）· 渡轮大楼",where:"Gott's Roadside Ferry Building San Francisco",price:'¥200–300',dish:'两个汉堡，共享一份薯条。',why:'替换生蚝午餐，不是额外吃一顿。',source:'https://www.gotts.com/location/sfferrybuilding/',tip:'柜台自取：可选0。'}]},
  {date:'9月30日',city:'硅谷 → 坎布里亚',low:800,high:1100,brief:'美式汉堡／月光石海滩海鲜',note:'早餐用安妮女王酒店已含早餐；车上备水果、水和面包。晚餐不晚于19:15到店。',meals:[
    {time:'10:50–11:35 · 提前午餐',name:"Gott’s Roadside（戈茨汉堡店）· 帕洛阿尔托",where:'855 El Camino Real Suite 65, Palo Alto',price:'¥220–300',dish:'汉堡、薯条或沙拉；奶昔两人共享即可。',why:'斯坦福体育场对面商场内，参观斯坦福后用餐，再去苹果游客中心。总停留45分钟，避免压缩海边日落。',source:'https://www.gotts.com/location/paloalto/',tip:'柜台自取：可选0。'},
    {time:'19:15–20:15 · 晚餐',name:'Moonstone Beach Bar & Grill（月光石海滩餐吧）',where:'6550 Moonstone Beach Dr, Cambria',price:'¥500–700',dish:'一份鱼类主菜、一份炸鱼薯条或海鲜，再共享汤。',why:'海滩日落后吃晚饭，离酒店约3公里。官方晚餐17:00–20:30，不能等到20:30才去；长途后不再开去其他小镇觅食。',source:'https://www.moonstonebeach.com/',tip:'桌边服务：税前18%–20%。'},
    {time:'晚餐备选',name:'Sea Chest Oyster Bar（海鲜箱生蚝餐厅）',where:'6216 Moonstone Beach Dr, Cambria',price:'¥550–800',dish:'熟海鲜主菜、生蚝按喜好少量点。',why:'以海鲜为主，但官网注明现金或支票付款；只在路过队伍短且现金足够时替换，不为网红店等位错过日落。',source:'https://www.seachestoysterbar.com/',tip:'桌边服务：税前18%–20%。'}]},
  {date:'10月1日',city:'圣塔芭芭拉 → 洛杉矶',low:600,high:850,brief:'海边船屋／好莱坞汉堡',note:'船屋作为早午餐；12:00前离开，保留好莱坞还车余量。豪华晚餐为替换项，默认预算不含。',meals:[
    {time:'10:45–11:45 · 早午餐',name:"Boathouse at Hendry’s Beach（亨德里海滩船屋餐厅）",where:'2981 Cliff Dr, Santa Barbara',price:'¥400–550',dish:'蟹饼类早餐或当日鱼类主菜、海鲜汤；按到店时早餐/午餐菜单点。',why:'同学推荐的海边餐厅，接在101号公路自驾中段。10:45未必供应午餐菜单；若等位超过20分钟，买简餐、海边短停后继续开车。',source:'https://boathousesb.com/menu',tip:'桌边服务：税前18%–20%。'},
    {time:'18:30 · 简单晚餐',name:'In-N-Out Burger（因安奥汉堡）· 好莱坞',where:'7009 Sunset Blvd, Hollywood',price:'¥150–220',dish:'两个双层牛肉汉堡、共享薯条；不必每人都加奶昔。',why:'酒店附近的加州连锁。选天还亮、主路人多时去，吃完回酒店；不为这一餐单独租车。',source:'https://locations.in-n-out.com/102-hollywood',tip:'柜台自取：不需小费。'},
    {time:'18:30 · 晚餐升级备选',name:'Musso & Frank Grill（穆索与弗兰克餐厅）',where:'6667 Hollywood Blvd, Hollywood',price:'¥900–1,300',dish:'牛排或美式主菜、蔬菜配菜，甜点共享。',why:'好莱坞老餐厅，酒店步行可达；周四17:00–23:00。想吃正式晚餐再订，第一天开车累就用汉堡方案。周一不开，不放10月5日。',source:'https://mussoandfrank.com/',xhs:'https://www.xiaohongshu.com/explore/650be4a30000000014024d59',tip:'桌边服务：税前18%–20%；相对汉堡额外预算单列。'}]},
  {date:'10月2日',city:'好莱坞环球影城',low:550,high:750,brief:'三把扫帚／回酒店简餐',note:'午餐放在上园游玩时，不为吃饭上下园折返。园内不安排长时间预约制餐厅。',meals:[
    {time:'13:30左右 · 午餐',name:'Three Broomsticks（三把扫帚餐厅）',where:'Three Broomsticks Universal Studios Hollywood',price:'¥330–450',dish:'烤鸡或炸鱼薯条，两份主食；黄油啤酒共享一杯。',why:'哈利·波特区域的主题餐厅。先玩下园，回上园看项目后再吃；小红书提到下午错峰可减少等位，但不保证当天队列。',source:'https://store.universalstudioshollywood.com/en/us/c/uh_ice_default_pb_extras',xhs:'https://www.xiaohongshu.com/explore/665b6c27000000000c019ab9',tip:'柜台点餐自取：可选0。'},
    {time:'18:30–19:30 · 晚餐',name:'In-N-Out Burger（因安奥汉堡）· 好莱坞',where:'7009 Sunset Blvd, Hollywood',price:'¥150–220',dish:'汉堡或按胃口减少主食。',why:'离园后回酒店再吃。若前一天已吃汉堡，就在城市大道选同价位柜台简餐，不专程跨城探店。',source:'https://locations.in-n-out.com/102-hollywood',tip:'柜台自取：不需小费。'}]},
  {date:'10月3日',city:'洛杉矶城市日',low:300,high:450,brief:'农夫市集／卡利米其林一星',note:'本日¥300–450仅含早餐、午餐和饮水；卡利晚餐¥1,380–1,620及小费¥220–280在预算另列。',meals:[
    {time:'11:00左右 · 午餐',name:'Pampas Grill（潘帕斯巴西烤肉）',where:'6333 W 3rd St, Los Angeles Pampas Grill',price:'¥220–320',dish:'按重量取餐，少量烤牛肉、米饭和蔬菜；先取少量，不堆满。',why:'位于始祖农夫市集，不增加交通。比再订一顿正式午餐省时，也给晚餐留胃口。',source:'https://farmersmarketla.com/merchants/pampas-grill',tip:'柜台按重结账：可选0。'},
    {time:'19:45 · 晚餐',name:'Kali Restaurant（卡利餐厅）',where:'5722 Melrose Ave, Los Angeles',price:'¥1,380–1,620',dish:'共享牛排、蔬菜或蘑菇配菜、招牌蛋白霜冰淇淋；按现行菜单点，不默认品鉴套餐。',why:'2026米其林官方仍标一星。安排在天文台之后，18:50前下山；优先预约19:45，两人、不配酒。',source:'https://guide.michelin.com/en/california/us-los-angeles/restaurant/kali',tip:'税前约20%；已另留¥220–280，不在餐费重复计入。'}]},
  {date:'10月4日',city:'迪士尼主园',low:600,high:800,brief:'星战卷饼／广场餐厅炸鸡',note:'午餐在西侧、晚餐靠城堡，减少往返。用餐和小吃合计计入当天预算，不另买餐饮套餐。',meals:[
    {time:'11:30–12:15 · 午餐',name:'Ronto Roasters（朗托烤肉店）',where:'Ronto Roasters Disneyland Park Anaheim',price:'¥220–300',dish:'烤肉香肠卷、饮水；不够再加一份共享，不要饿着等午后长队。',why:'位于银河边缘，接在西侧项目之后；支持应用内查看菜单及取餐时段。先确认可取餐再移动。',source:'https://disneyland.disney.go.com/dining/disneyland/ronto-roasters/',tip:'柜台自取：可选0。'},
    {time:'17:45–18:30 · 晚餐',name:'Plaza Inn（广场餐厅）',where:'Plaza Inn Disneyland Park Anaheim',price:'¥280–380',dish:'炸鸡套餐；胃口较小时一份炸鸡加另一份主食或沙拉共享。',why:'靠主街和城堡，接明日世界项目、晚饭后直接等表演。午晚餐为柜台形式，不是高价人物互动早餐；现场点餐，别等手机点餐入口。',source:'https://disneyland.disney.go.com/dining/disneyland/plaza-inn/menus/lunch%20and%20dinner/',xhs:'https://www.xiaohongshu.com/explore/67ee1852000000001c0179de',tip:'普通柜台午晚餐：可选0；特殊套餐另看条款。'}]},
  {date:'10月5日',city:'洛杉矶购物与海边',low:750,high:1050,brief:'共和国早午餐／海边墨西哥餐',note:'不为早餐提前起床。10:15先早午餐，再购物；罗迪欧大道只补咖啡，17:00先吃晚饭再拍日落。',meals:[
    {time:'10:15–11:15 · 早午餐',name:'République（共和国餐厅）',where:'624 S La Brea Ave, Los Angeles',price:'¥280–420',dish:'咸味鸡蛋主食、可颂或糕点、两杯咖啡；糕点共享。',why:'咖啡烘焙区每天08:00–14:00，周一可吃早午餐。拱廊、柜台适合拍照；排队超过25分钟就转柜台打包，避免挤掉购物。',source:'https://republiquela.com/cafe-bakery/',xhs:'https://www.xiaohongshu.com/explore/60c19a2a000000000102552b',tip:'纯柜台自取可选0；若有桌边服务按税前18%–20%。'},
    {time:'17:00–18:00 · 提前晚餐',name:'Blue Plate Taco（蓝盘墨西哥餐厅）',where:'1515 Ocean Ave, Santa Monica',price:'¥380–550',dish:'鱼肉或虾肉塔可、鳄梨酱；不点酒也可以。',why:'在码头附近，吃完回海滩等日落。周一12:00–22:00；16:00–18:00有欢乐时段，优惠菜品到店确认。',source:'https://www.blueplatetaco.com/location/blue-plate-tacos/',tip:'桌边服务：税前18%–20%。'}]},
  {date:'10月6日',city:'洛杉矶 → 拉斯维加斯',low:480,high:650,brief:'机场简餐／酒店旁卷饼或汉堡',note:'晚餐以人民币250元／两人合计为目标，以下三家选一家，不叠加。全天预算另含早餐、机场简餐及饮水。价格为点单估算，按1美元＝6.7元、含税、不含酒；不是已核实的当日菜单报价。16:45用餐，17:30前结束，为直升机留出交通时间。',meals:[
    {time:'综合第1 · 16:45–17:30',name:'Jaburritos（日式寿司卷饼店）',where:'Jaburritos 3545 Las Vegas Blvd S Suite L12 Las Vegas',price:'¥240–300',dish:'每人一份寿司卷饼或饭碗；不额外点小吃、酒和套餐饮料。可选熟鸡肉，不必吃生鱼。',why:'位于 LINQ Promenade（林克步行街），从弗拉明戈酒店预留10–15分钟步行。Google Maps（谷歌地图）4.5／5，2,042条评价（9月22日核查）。近期1—2周评论提到分量、口味和服务；也有近一个月评价称一碗约24美元，加料并不一定便宜。两份主食接近250元目标，较贵鱼类或加料可能超过；付款前看菜单总价。官网周二营业11:00—23:00，仅接受非现金支付，带银行卡。',booking:'无需提前订位，现场点单；排队超过20分钟换店。',source:'https://www.jaburritos.com/menu/',review:'https://www.tripadvisor.ie/Restaurant_Review-g45963-d12188625-Reviews-or15-Jaburritos-Las_Vegas_Nevada.html',tip:'柜台点餐自取，小费可选0；两人预计总支出人民币240–300元。'},
    {time:'综合第2 · 价格更低',name:'In-N-Out Burger（因安奥汉堡）· 林克步行街店',where:'In-N-Out Burger 3545 Las Vegas Blvd S Suite L24 Las Vegas',price:'¥160–220',dish:'两个汉堡、一份共享薯条；饮料按需要点，不额外加奶昔。',why:'同在林克步行街，从酒店预留10–15分钟步行。Google Maps（谷歌地图）4.5／5，15,315条评价（9月22日核查）。可见评价提到晚间拥挤、可能拼桌，不保证有座。适合想控制餐费、不安排正式堂食的一晚；排队超过20分钟就换卷饼店。',booking:'不订位，现场排队点单；不为等座拖延直升机报到。',source:'https://locations.in-n-out.com/320',review:'https://www.tripadvisor.com/Restaurant_Review-g45963-d12091312-Reviews-In_N_Out_Burger_LINQ_PROMENADE-Las_Vegas_Nevada.html',tip:'柜台自取，不需小费；两人预计总支出人民币160–220元。'},
    {time:'综合第3 · 仅作就近备选',name:'Haute Doggery（豪特热狗店）',where:'Haute Doggery LINQ Promenade Las Vegas',price:'¥180–250',dish:'每人一份热狗，共享薯条；不点酒，若仍饿再加主食并相应增加预算。',why:'同在林克步行街，不用为换餐厅打车。Google Maps（谷歌地图）4.0／5，744条评价（9月22日核查）。可见评价对热狗本身、座位环境及等餐时间有分歧，排在前两家之后。适合想换口味时选择，不作为专程打卡点。',booking:'无需提前订位，柜台点单；只在想吃热狗或前两家排队时选。',source:'https://www.hautedoggerylv.com/menu',review:'https://www.tripadvisor.co.uk/Restaurant_Review-g45963-d5994117-Reviews-Haute_Doggery-Las_Vegas_Nevada.html',tip:'柜台自取，小费可选0；两人预计总支出人民币180–250元。'}]},
  {date:'10月7日',city:'羚羊谷一日团',low:320,high:500,brief:'随团午餐／回酒店汉堡',note:'早餐前晚买好；午餐按已选含餐团处理，已计团费，不重复预算。若实际订的团不含餐，再补两人¥150–220。',meals:[
    {time:'22:00左右 · 回程晚餐',name:'Gordon Ramsay Burger（戈登·拉姆齐汉堡）· 弗拉明戈店',where:'Gordon Ramsay Burger Flamingo Las Vegas',price:'¥250–380',dish:'两个汉堡或按胃口减量。',why:'品牌开业公告营业10:00–24:00；长途团可能晚到，不做不可退订位。若超过23:00或厨房提早截单，用前晚准备的即食食品，不再跑远。',source:'https://investor.caesars.com/news-releases/news-release-details/gordon-ramsay-burger-celebrates-its-grand-opening-flamingo-las',tip:'桌边服务：税前18%–20%；外带可选0。'}]},
  {date:'10月8日',city:'巨型球 → 换酒店 → 《O》',low:650,high:900,brief:'威尼斯人午餐／百乐宫晚餐',note:'11:00巨型球、18:30《O》。午餐后取行李、换酒店；17:20左右先补小点心，正式晚餐放看秀后。',meals:[
{time:'12:45–13:45 · 午餐',name:'Grand Lux Cafe（豪华咖啡馆）· 威尼斯人店',where:'Grand Lux Cafe Venetian 3355 Las Vegas Blvd S',price:'¥250–350',dish:'两份基础汉堡或三明治，不点前菜、酒及甜点；价格为估算，按当天菜单调整。',why:'看完球步行去威尼斯人。13:45前吃完，再短逛30分钟；候位超过15分钟改商场柜台简餐。',source:'https://locations.grandluxcafe.com/nv/las-vegas/1/',booking:'以现场候位为主，不锁不可取消套餐。',tip:'桌边服务按税前18%–20%，另预留两人约人民币45–65元。'},
{time:'20:15–21:00 · 晚餐',name:'Noodles（面）· 百乐宫',where:'Noodles Bellagio Las Vegas',price:'¥300–450',dish:'两份汤面或饭；不额外点酒。',why:'《O》散场后同酒店用餐，不跨酒店找餐厅。若等位超过20分钟，改酒店柜台简餐；前往枫丹白露的车程另留余量。',source:'https://bellagio.mgmresorts.com/en/restaurants/noodles.html',booking:'建议提前查看20:15可订时段；是否接受订位及可用库存以官网为准，不保证已订。',tip:'桌边服务按税前18%–20%，另预留两人约人民币50–80元。'}]},
  {date:'10月9日',city:'艺术区 → 奥特莱斯 → 酒店',low:500,high:750,brief:'艺术区咖啡／购物简餐／酒店晚餐',note:'今天购物与休闲，不安排演唱会。午餐在奥特莱斯按现场营业档口选择，两人留人民币180–250元，不为吃饭再跨区。',meals:[
{time:'10:30–11:15 · 咖啡与轻食',name:'Bungalow Coffee（平房咖啡馆）',where:'Bungalow Coffee 201 E Charleston Blvd Las Vegas',price:'¥120–180',dish:'咖啡和一份共享轻食；不是再吃一顿完整午餐。',why:'艺术区起点；若上午改为射击，这段删除，餐费不叠加。',source:'https://bungalowcoffeeco.com/',booking:'普通咖啡轻食无需提前订位，现场点单。',tip:'柜台自取可选0。'},
{time:'18:00左右 · 晚餐',name:'Promenade Food Hall（长廊美食广场）',where:'Fontainebleau Las Vegas Promenade Food Hall',price:'¥200–280',dish:'两份饭面、披萨或汉堡，按当天食欲选。',why:'在住宿酒店内吃，晚餐后整理行李，不再赶演出。',source:'https://www.fontainebleaulasvegas.com/dining/',booking:'柜台简餐无需订位，具体档口营业以酒店当天为准。',tip:'柜台自取可选0。'}]},
  {date:'10月10日',city:'拉斯维加斯 → 纽约',low:650,high:900,brief:'机场便餐／韩国城热汤',note:'含机场早餐及途中简餐约¥300–450；纽约当晚不安排远处网红店。',meals:[
    {time:'20:45–21:30 · 晚餐',name:'BCD Tofu House（北仓洞嫩豆腐）· 曼哈顿店',where:'5 W 32nd St, New York',price:'¥300–450',dish:'两份嫩豆腐汤配米饭；牛肉、海鲜或不辣口味。',why:'距勒苏蕾酒店几条街，在韩国城。官方营业09:30–次日01:30；抵达晚仍有余量。吃完走主路回酒店，不再去时代广场。',source:'https://www.bcdtofuhouse.com/tristate',tip:'桌边服务：税前18%–20%。'}]},
  {date:'10月11日',city:'纽约下城与丹波区',low:650,high:900,brief:'贝果／布鲁克林披萨',note:'早餐或下城午餐选简餐约¥180–280；把坐下吃饭的时间留给丹波区傍晚。',meals:[
    {time:'07:00 · 房间早餐',name:'提前采购早餐',where:'Executive Hotel Le Soleil New York',price:'¥80–140',dish:'常温面包、水果和饮水。',why:'10日可在出发机场购买常温食品；抵达纽约较晚，不再去已关门的贝果店。11日化妆前吃完，08:20出门。',tip:'无需小费。'},
    {time:'17:15 · 提前晚餐',name:"Juliana’s Pizza（朱莉安娜披萨）",where:'19 Old Fulton St, Brooklyn',price:'¥320–480',dish:'一份大披萨和一份沙拉共享。',why:'在布鲁克林大桥脚下，17:15—18:00用餐，18:10后再按体力走桥回曼哈顿。每天11:30–15:15、16:00–21:00；避开下午停炉。排队超过30分钟换下方美食市场。',source:'https://www.julianaspizza.com/',tip:'桌边服务：税前18%–20%。'},
    {time:'晚餐等位备选',name:'Fornino（弗尼诺披萨）· 时代美食市场',where:'Time Out Market New York 55 Water St Brooklyn Fornino',price:'¥280–420',dish:'披萨、沙拉或市场其他档口简餐。',why:'同在丹波区，不回曼哈顿绕路。市场屋顶看桥景；这里是弗尼诺，不是已关闭的朱莉安娜市场分店。',source:'https://www.timeout.com/time-out-market-new-york/restaurants/fornino',tip:'柜台自取：可选0。'}]},
  {date:'10月12日',city:'中央公园与NBA球赛',low:500,high:750,brief:'清真鸡肉饭／赛前纽约披萨',note:'球赛日不约慢节奏晚餐。正常两餐约¥350–550，余量用于早餐、咖啡和场内饮水。',meals:[
    {time:'12:30 · 午餐',name:'The Halal Guys（清真兄弟）· 原始餐车',where:'The Halal Guys W 53rd St and 6th Ave New York',price:'¥180–270',dish:'鸡肉或混合肉盖饭；白酱适量、红辣酱少量试。',why:'中央公园南侧到第五大道途中，体现纽约街头餐饮。外带餐车，无舒适堂食；遇下雨或不想站着吃，就改附近咖啡馆简餐。',source:'https://thehalalguys.com/locations/west-53rd-street-new-york/',tip:'柜台自取：可选0。'},
    {time:'17:15–17:50 · 赛前晚餐',name:'NY Pizza Suprema（纽约至上披萨）',where:'413 8th Ave, New York',price:'¥170–260',dish:'先点3–4片披萨共享，再按胃口加；一片芝士、一片肉类。',why:'就在麦迪逊广场花园附近，先吃再过安检，避免把正餐放进球馆高价餐饮。按门票实际开赛时间，将晚餐放在开赛前至少90分钟。',source:'https://nypizzasuprema.com/',tip:'柜台自取：可选0。'}]},
  {date:'10月13日',city:'纽约西侧 → 机场酒店',low:600,high:850,brief:'切尔西塔可／机场酒店晚餐',note:'16:00回酒店取行李、17:00出发去机场区。机场酒店名称尚未提供，晚餐不编造具体店名；已预留¥250–350。',meals:[
    {time:'08:30 · 早餐',name:'Best Bagel & Coffee（百思贝果咖啡）',where:'225 W 35th St, New York',price:'¥120–180',dish:'贝果和咖啡，或用前晚买的面包替换。',why:'退房寄存前顺路采购；周二06:00–17:00营业。',source:'https://bestbagelandcoffee.com/',tip:'柜台自取：可选0。'},
    {time:'11:30–12:15 · 午餐',name:'Los Tacos No.1（第一塔可店）· 切尔西市场',where:'75 9th Ave, New York Los Tacos No.1',price:'¥220–300',dish:'牛肉、烤猪肉或鸡肉塔可，各买几只共享。',why:'高线公园下到切尔西市场后直接吃，11:00–22:00。小红书有好评也有觉得普通的评价；这是顺路简餐，不排一小时。以站食为主，随后找座位休息。',source:'https://www.lostacos1.com/location/los-tacos-chelsea-market/',xhs:'https://www.xiaohongshu.com/explore/67a25b1d0000000029027aa3',tip:'柜台自取：可选0。'}]},
  {date:'10月14日',city:'返程',low:50,high:100,brief:'便携早餐／飞机餐',note:'06:30航班。前晚备面包，饮水过安检后补；不假设凌晨机场餐厅都已营业，飞机餐不重复计费。',meals:[]}
];

const diningLink = (url,label) => `<a target="_blank" rel="noopener" href="${url.replaceAll('&','&amp;')}">${label}</a>`;
// Ranking reflects this dinner's budget and departure deadline, not stars alone.
diningDays.find(d=>d.date==='10月6日').note += ' 综合排序依据：谷歌评分及评价数量、实际点单预算、步行位置、排队风险。三家均在林克步行街，步行预留10—15分钟为酒店出发的计划余量，不是实时导航值。另比较了 Gordon Ramsay Burger（拉姆齐汉堡，4.7分／3,784条）、Yard House（庭院餐厅，4.5分／7,072条）及 Battista’s Hole in the Wall（巴蒂斯塔意大利餐厅，4.5分／8,469条）：地图人均分别为20—60、20—30、30—40美元，且堂食需另留小费，故不作为两人250元这顿的首选。拉姆齐和巴蒂斯塔地图提供订位入口，若改去建议提前订；本次不替你预订。评分为9月22日页面快照，价格档位为用户报告，不等于含税结账价。';
const diningRange = d => `人民币 ${d.low.toLocaleString('zh-CN')}–${d.high.toLocaleString('zh-CN')} 元`;
const diningCards = d => d.meals.map(m=>`<article class="meal-card"><span class="meal-time">${m.time}</span><h4>${m.name}</h4><b class="meal-price">人民币 ${m.price.replace('¥','')} 元<small> / 两人合计，含税、不含小费</small></b><p><b>点什么：</b>${m.dish}</p><p>${m.why}</p>${m.booking?`<p><b>是否预订：</b>${m.booking}</p>`:''}<p class="meal-tip">${m.tip}</p><div class="meal-links">${diningLink('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(m.where),'地图与近期评价')}${diningLink(m.source,'官方资料')}${m.review?diningLink(m.review,'评价来源'):''}${m.xhs?diningLink(m.xhs,'小红书参考'):''}</div></article>`).join('');
document.querySelectorAll('#daily article.day').forEach((day,i)=>{
  const d=diningDays[i]; if(!d)return;
  day.id='itinerary-day-'+i;
  day.querySelector('.day-body').insertAdjacentHTML('beforeend',`<details class="daily-dining" id="dining-day-${i}"><summary><span><b>餐厅与餐饮预算</b><small>${d.brief}</small></span><strong>${diningRange(d)}</strong></summary><div class="dining-inner"><p class="dining-note">${d.note}</p><div class="meal-grid">${diningCards(d)}</div></div></details>`);
});
const foodLow=diningDays.reduce((s,d)=>s+d.low,0),foodHigh=diningDays.reduce((s,d)=>s+d.high,0);



document.querySelector('#la .section-head').insertAdjacentHTML('afterend',`<article class="ticket-confirmation" id="dated-park-tickets"><div class="ticket-confirm-head"><span class="badge orange">2026年9月22日官网核价</span><h3>乐园门票：日期不调整</h3><p>10月2日环球影城，10月4日迪士尼主园。均为两位成人；下列为当前官网选择页小计，尚未购买，最终按付款页结算。</p></div><div class="table-wrap"><table><thead><tr><th>日期 / 园区</th><th>购买选项</th><th>两人官网小计</th><th>人民币预算</th></tr></thead><tbody><tr><td><b>10月2日 · 周五</b><br>Universal Studios Hollywood（好莱坞环球影城）</td><td>1-Day General Admission（单日普通门票）× 2<br>每人129.95美元</td><td>259.90美元</td><td><b>¥1,741.33</b></td></tr><tr><td><b>10月4日 · 周日</b><br>Disneyland Park（迪士尼乐园主园）</td><td>1-Day, 1-Park Ticket（单日单园票）× 2<br>每人184美元</td><td>368美元</td><td>¥2,465.60</td></tr><tr><td>迪士尼推荐加购</td><td>Lightning Lane Multi Pass（闪电通道多项目通票）× 2<br>每人34美元；两人各需一份</td><td>68美元</td><td>¥455.60</td></tr><tr class="ticket-total"><td colspan="2"><b>推荐合计：环球普通票 + 迪士尼主园及多项目通票</b></td><td>695.90美元</td><td><b>¥4,662.53</b></td></tr></tbody></table></div><div class="meal-grid"><div class="ticket-choice"><h4>环球：先买普通票</h4><p>同日 Universal Express（环球快速通行票）249.95美元/人，两人¥3,349.33，已经包含入园门票。与普通票差额<b>¥1,608</b>，不是再加两张完整快速票。</p><p>本方案把影城之旅、哈利·波特、任天堂作为重点；不承诺刷完所有项目。要明显减少排队，可直接改买快速通行票。现场升级受库存和当日报价影响，不能保证仍是这个差额。</p><p>普通快速通行不含 Fast &amp; Furious: Hollywood Drift（速度与激情：好莱坞漂移）的快速队列；该新项目按现场普通队列和体力选玩。普通票不含 Halloween Horror Nights（万圣节惊魂夜）。</p>${diningLink('https://store.universalstudioshollywood.com/en/us/store/c/uh_ice_default_pb_tickets','环球官方购票')}</div><div class="ticket-choice"><h4>迪士尼：主园 + 两份多项目通票</h4><p>主园及通票两人<b>436美元 / ¥2,921.20</b>。不买跨园、不买加州冒险乐园派对票、不买停车券；酒店往返用网约车。</p><p>购票日期和公园预约都选10月4日主园；付款后检查两张票及预约。多项目通票含当天官方摄影照片数字下载，入园后开始约项目。</p><p>Star Wars: Rise of the Resistance（星球大战：抵抗组织崛起）不在多项目通票内。先走开园普通队列；单项目通票按入园当天应用报价，当前不把未知价格写成已确认价。</p>${diningLink('https://disneyland.disney.go.com/admission/tickets/','迪士尼官方购票')}</div></div><details class="ticket-compare"><summary>为什么不换成10月2日迪士尼、10月4日环球？</summary><div class="table-wrap"><table><thead><tr><th>方案</th><th>环球两人</th><th>迪士尼两人（含多项目通票）</th><th>合计</th></tr></thead><tbody><tr><td>原安排：2日环球、4日迪士尼</td><td>259.90美元</td><td>436美元</td><td>¥4,662.53</td></tr><tr><td>对调：2日迪士尼、4日环球</td><td>279.90美元</td><td>406美元</td><td>¥4,595.53</td></tr></tbody></table></div><p>对调只省¥67。1日开车到洛杉矶，2日去离酒店近的环球；3日城市活动，4日再早起去迪士尼，更利于恢复。5日迪士尼仍为184美元/人，没有价格优势，还会压缩次日飞拉斯维加斯前的休息。</p></details><p class="ticket-footnote">汇率统一按6.7预算。官网普通票与附加服务有不可退款限制；只核价、未提交订单。园区开放时间、项目停运及表演时刻以官方日历和应用为准。</p></article>`);

document.getElementById('dated-park-tickets').insertAdjacentHTML('beforeend', `<div class="ticket-footnote"><b>当日运营：</b>环球10月2日09:00—18:00；迪士尼10月4日08:00—22:00，烟花21:30。迪士尼当日印第安纳琼斯冒险、疯狂茶杯列为暂停开放；已调整逐日路线。${diningLink('https://www.universalstudioshollywood.com/web/en/us/sales/calendar-and-hours','环球官方日历')} · ${diningLink('https://disneyland.disney.go.com/calendars/day/2026-10-04/','迪士尼10月4日日历')}</div>`);
